# Enigma Build workflow task
name: build

# build on pushs and pull requests on master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# platform tasks
jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [Win32, x64]
    defaults:
      run:
        shell: cmd
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with: 
        vs-version: '16.8' #using vs 16.8.3 in my local machine Help -> About Microsoft Visual Studio


    - name: Generate Project Files
      run: ./Gen-Windows-vs2019.bat

    - name: Build Solution
      run: msbuild Enigma.sln -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo 

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Installing Latest gcc & g++ Compiler
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install gcc-10 g++-10

    - name: Installing necessary system libraries
      run: sudo apt install libgl1-mesa-dev libxi-dev libx11-dev libxcursor-dev libxrandr-dev libxcomposite-dev libxinerama-dev

    - name: Extracting premake5 binary
      run: tar xvzf ./Premake/Linux/premake-5.0.0-alpha15-linux.tar.gz -C ./Premake/Linux/

    - name: Generating Makefiles
      run: sudo bash ./Gen-Linux-Makefile.sh

    - name: Make Enigma
      run: make config=release CC=gcc-10 CPP=g++-10


#    - name: Generate Project Make Files
#      run: |
#        sudo apt-get update
#        sudo ./Gen-Linux-Makefile.sh
#
#    - name: Make Project
#      run: |
#        make
#
#
#    # update os and install Premake5
#    # https://zoomadmin.com/HowToInstall/UbuntuPackage/premake
#    - name: Install Dependencies
#      run: |
#        sudo apt-get update -y
#        sudo apt-get install -y premake
#
#    # generate project Makefiles and make executable
#    - name: Build Enigma g++ 64-bit
#      run: |
#        g++ --version
#        premake5 gmake2
#        make
# TODO
#  MacOSX:
#    runs-on:
